# Generated by Django 4.2.25 on 2025-10-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cspreport',
            name='blocked_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspreport',
            name='document_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspreport',
            name='violated_directive',
            field=models.TextField(blank=True, null=True),
        ),
    ]
