# Generated by Django 5.2.7 on 2026-09-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("csp_reporting", "0002_cspreport_blocked_uri_cspreport_document_uri_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cspreport",
            options={"verbose_name": "CSP Report", "verbose_name_plural": "Reports"},
        ),
    ]
