# Generated by Django 5.2.17 on 2026-09-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_reporting', '0002_cspreport_blocked_uri_cspreport_document_uri_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cspreport',
            options={'ordering': ['-received_at'], 'verbose_name': 'CSP Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterField(
            model_name='cspreport',
            name='blocked_uri',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cspreport',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cspreport',
            name='violated_directive',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='cspreport',
            index=models.Index(fields=['-received_at'], name='csp_reporti_receive_466eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='cspreport',
            index=models.Index(fields=['violated_directive', '-received_at'], name='csp_reporti_violate_a904b9_idx'),
        ),
        migrations.AddIndex(
            model_name='cspreport',
            index=models.Index(fields=['blocked_uri', '-received_at'], name='csp_reporti_blocked_8b7a54_idx'),
        ),
    ]
